### ISSUE TITLE
installUserAndRightsModule.bat

### ISSUE THREAD

**Issue by Chintsin** [kevindaus/tomblocator#1]
sir this is hannah of sb..download the project and it's lacking the file installUserAndRightsModule.bat ..can you please reupload? thanks...

**Comment by kevindaus** [comment]
@Chintsin  - Hi hananah , the batch file is added now it is under **protected/** folder
make sure you configured the db connection right before running the installUserAndRightsModule.bat If you got further question please don't hesitate to comment


FIXED at commit https://github.com/kevindaus/tomblocator/commit/485f9f7b215588b409bcc6b7a605fed9515d7438

**Comment by Chintsin** [comment]
wooh super thanks sir...i have run your project with no errors now :) now i know what will be the content of my system ...very much thankful :)

**Comment by Chintsin** [comment]
![image](https://user-images.githubusercontent.com/35422532/35393574-4bef05c2-0220-11e8-9652-918db0341c8c.png)


sir sorry for interrupting again...but it show this error when logging out coz there is no logout controller,,

![image](https://user-images.githubusercontent.com/35422532/35393648-88f8c174-0220-11e8-9053-e73c022a263c.png)

**Comment by kevindaus** [comment]
I created another issue ticket for the error and added the **solution** as well. [ Click here. ](https://github.com/kevindaus/tomblocator/issues/2).
