### ISSUE TITLE
map creator

### ISSUE THREAD

**Issue by Chintsin** [kevindaus/tomblocator#4]
Hi Sir..tanong lang po sana ako ulit kung pano mo ginawa yung map mo diba svg map yun? ask lg sana ako kng anong software po yung ginamit niyo ... illustrator din po ba?thanks :)

**Comment by Chintsin** [comment]
ok na pla sir tnx ;) png nlg ginamit xD

**Comment by kevindaus** [comment]
bro. sorry super late reply. 
I never noticed your query.  

**To answer your question .** 

I think I made use of high resolution image for this then I made use of 
https://www.maptiler.com/download/ to generate the zoom image

then using leaflet js . 

You may also use : 
https://openlayers.org/

**Comment by fredsayson** [comment]
> Hi Sir..tanong lang po sana ako ulit kung pano mo ginawa yung map mo diba svg map yun? ask lg sana ako kng anong software po yung ginamit niyo ... illustrator din po ba?thanks :)

bro patanung lng po i really need your help kasi .. about sa tabulation-master na system bro nakita ko yung comment mo about sa judge . bdw paano nga pala makita or ma access ang judge panel bro ??? please help me i really need you bro :(
